<?php

use Illuminate\Database\Seeder;

class SectionImgTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 1;
        $sImg->siGId = 1;
        $sImg->siOrder = 1;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 1;
        $sImg->siGId = 11;
        $sImg->siOrder = 2;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 1;
        $sImg->siGId = 3;
        $sImg->siOrder = 3;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 1;
        $sImg->siGId = 4;
        $sImg->siOrder = 4;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 1;
        $sImg->siGId = 5;
        $sImg->siOrder = 5;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();
/////////////////////////////////////////////////////////////////
        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 3;
        $sImg->siGId = 6;
        $sImg->siOrder = 1;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 3;
        $sImg->siGId = 7;
        $sImg->siOrder = 2;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 3;
        $sImg->siGId = 8;
        $sImg->siOrder = 3;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 3;
        $sImg->siGId = 9;
        $sImg->siOrder = 4;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 3;
        $sImg->siGId = 10;
        $sImg->siOrder = 5;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();
        /////////////////////////////////////
        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 4;
        $sImg->siGId = 1;
        $sImg->siOrder = 1;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 4;
        $sImg->siGId = 2;
        $sImg->siOrder = 2;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 4;
        $sImg->siGId = 3;
        $sImg->siOrder = 3;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 4;
        $sImg->siGId = 4;
        $sImg->siOrder = 4;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 4;
        $sImg->siGId = 5;
        $sImg->siOrder = 5;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 4;
        $sImg->siGId = 6;
        $sImg->siOrder = 5;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 4;
        $sImg->siGId = 7;
        $sImg->siOrder = 5;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 4;
        $sImg->siGId = 8;
        $sImg->siOrder = 5;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        /////////////////////////////////////////////////////////////////////
        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 7;
        $sImg->siGId = 1;
        $sImg->siOrder = 1;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 7;
        $sImg->siGId = 11;
        $sImg->siOrder = 2;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 7;
        $sImg->siGId = 3;
        $sImg->siOrder = 3;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 7;
        $sImg->siGId = 4;
        $sImg->siOrder = 4;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 7;
        $sImg->siGId = 5;
        $sImg->siOrder = 5;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();
        /////////////////////////////////////////////////////////////////
        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 9;
        $sImg->siGId = 6;
        $sImg->siOrder = 1;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 9;
        $sImg->siGId = 7;
        $sImg->siOrder = 2;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 9;
        $sImg->siGId = 8;
        $sImg->siOrder = 3;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 9;
        $sImg->siGId = 9;
        $sImg->siOrder = 4;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();

        $sImg = new \Hamedan_2018\SectionImg;
        $sImg->siSId = 9;
        $sImg->siGId = 10;
        $sImg->siOrder = 5;
        $sImg->siFaAlt = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnAlt = 'Events and festivals in Hamadan';
        $sImg->siArAlt = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaSubject = 'رویدادها و جشنواره ها در همدان';
        $sImg->siEnSubject = 'Events and festivals in Hamadan';
        $sImg->siArSubject = 'الأحداث والمهرجانات في همدان';
        $sImg->siFaDescription = 'افتخار دارد که میزبان رویدادهای بین المللی در طول سال باشد. این جشنواره ها یک مقصد توریستی است که فرصت مهمی برای مهمانان فراهم می کند.';
        $sImg->siEnDescription = 'Hamadan is proud to host international events throughout the year. These festivals are a tourist destination that offers guests an important opportunity.';
        $sImg->siArDescription = 'الفعاليات الدولية على مدار العام. هذه المهرجانات هي وجهة سياحية التي توفر للضيوف فرصة هامة.';
        $sImg->save();
    }
}
